#
# Makefile for the Novatek NT36536 touchscreen driver.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_NT36532_SPI) += nt36532_ts.o
nt36532_ts-y := nt36xxx.o nt36xxx_fw_update.o
